# Note: this is the grey module
#esp32:
  #board: m5stack-atom
  #framework:
    #type: esp-idf
###
# Uart Settings
###
uart:
  id: uart_modbus
  tx_pin: GPIO19
  rx_pin: GPIO22
  baud_rate: 19200
  data_bits: 8
  stop_bits: 1
  parity: EVEN
  debug:
    direction: BOTH
